In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import linear_model
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix
import re
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data=pd.read_excel("Training set.xlsx",sheet_name="Training Set",usecols=("PRODUCT_DESCRIPITION","Classifed"))

In [ ]:
data.head()

PRODUCT_DESCRIPITION                   Classifed
0         2 METHYL 1, 3 PROPANEDIOL (TANK CONTAINER)                         NaN
1  PHTHALIC ANHYDRIDE [KOREA INDIA CEPA NO. K001 ...          PHTHALIC ANHYDRIDE
2        PENTAERYTHRITOL MONO GRADE (CAS NO.115 775)  PENTAERYTHRITOL MONO GRADE
3        PENTAERYTHRITOL MONO GRADE (CAS NO.115 775)  PENTAERYTHRITOL MONO GRADE
4  MONO PROPYLENE GLYCOL USP (INDUSTRIAL PERFUMER...                         NaN

In [ ]:
data["PRODUCT_DESCRIPITION"] = data["PRODUCT_DESCRIPITION"].str.replace('[^a-zA-Z\d\s+]',"")
data["PRODUCT_DESCRIPITION"] = data["PRODUCT_DESCRIPITION"].apply(lambda x: re.sub('\d\d\d\d\d\d+', '',x))
data["Classifed"] = data["Classifed"].fillna("None")

In [ ]:
data["Classifed"].unique()

array(['None', 'PHTHALIC ANHYDRIDE', 'PENTAERYTHRITOL MONO GRADE',
       'Isophthalic Acid', 'Benzoic acid', 'DIACETONE ACRYLAMIDE',
       'Propylene Glycol', 'Crude Soya', 'Refined Soybean Oil',
       'Crude Linseed OIL', 'CASTOR OIL', 'DCO', 'GLYCEROL', 'GLYECERIN',
       'GLYCERIN', 'COCONUT FATTY ACID', 'SUN ACID OIL', 'PALM ACID OIL',
       'SOYA ACID OIL', 'Hydragloss', 'Kaolin Other', 'Polygloss',
       'Neogen', 'Britex-96', 'RB Gloss', 'Britex-98', 'Uncoated Other',
       'Omyacarb', 'Coated M-10', 'PCC', 'GCC', 'omyalite',
       'zancarb coated M-10', 'Texanol', 'Alcohol ester', 'NX795',
       'Ruanta C12', 'TMPD', 'Optifilm Enhancer', 'TXIB', 'C16', 'C-12',
       'C-16', 'Alcohol Ester12', 'Rhodacal DS4AP', 'BYK XXX', 'Dowfax',
       'Calfax', 'Nuosperse FA 196', 'Capstone FS64', 'Rhodacal SSA',
       'Rhodacal DS10', 'Bermocoll ***', 'NA ', 'Natrosol ***',
       'Tylose ***', 'HEC H200K', 'HEC B100K', 'HEC B15KC',
       'Combizell MHEC 40000', 'HEC', 'FMC 2500

In [ ]:
fe = TfidfVectorizer(
    min_df=1,
    max_df=1.0,
    ngram_range=(1, 4),
    max_features=5000,
    stop_words=ENGLISH_STOP_WORDS,
    decode_error='ignore'
)

In [ ]:
fe

TfidfVectorizer(analyzer='word', binary=False, decode_error='ignore',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=5000,
                min_df=1, ngram_range=(1, 4), norm='l2', preprocessor=None,
                smooth_idf=True,
                stop_words=frozenset({'a', 'about', 'above', 'across', 'after',
                                      'afterwards', 'again', 'against', 'all',
                                      'almost', 'alone', 'along', 'already',
                                      'also', 'although', 'always', 'am',
                                      'among', 'amongst', 'amoungst', 'amount',
                                      'an', 'and', 'another', 'any', 'anyhow',
                                      'anyone', 'anything', 'anyway',
                                      'anywhere', ...}),
                strip_accents=None, sublinear_tf=False,
                token_pa

In [ ]:
x_data = fe.fit_transform(data["PRODUCT_DESCRIPITION"])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x_data, data['Classifed'], test_size=0.2, random_state=1)

In [ ]:
X_train.shape, X_test.shape,y_train.shape, y_test.shape

((34556, 5000), (8639, 5000), (34556,), (8639,))

In [ ]:
clf = OneVsRestClassifier(estimator=LogisticRegression(C=59.94842503189409, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l1',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False))

In [ ]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


OneVsRestClassifier(estimator=LogisticRegression(C=59.94842503189409,
                                                 class_weight=None, dual=False,
                                                 fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l1',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [ ]:
predicted = clf.predict(X_test)

In [ ]:
print(classification_report(y_test, predicted))

                            precision    recall  f1-score   support

           Alcohol Ester12       0.00      0.00      0.00         2
             Alcohol ester       0.93      0.93      0.93        15
                   BYK XXX       0.67      0.67      0.67         6
              Benzoic acid       1.00      0.96      0.98        46
             Bermocoll ***       0.97      0.97      0.97        35
                 Britex-96       1.00      1.00      1.00        13
                      C-12       0.00      0.00      0.00         8
                      C-16       1.00      0.50      0.67         4
                       C16       1.00      1.00      1.00         1
                CASTOR OIL       0.97      0.98      0.98       215
        COCONUT FATTY ACID       1.00      1.00      1.00        40
                    Calfax       1.00      1.00      1.00         9
             Capstone FS64       0.00      0.00      0.00         1
               Coated M-10       1.00      0.98

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
print(confusion_matrix(y_test, predicted))

[[  0   1   0 ...   0   0   0]
 [  0  14   0 ...   0   0   0]
 [  0   0   4 ...   0   0   0]
 ...
 [  0   0   0 ... 778   0   0]
 [  0   0   0 ...   1  24   0]
 [  0   0   0 ...   0   0   9]]
